<?php

namespace Tests\Unit;

use App\Answer;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class AnswerTest extends TestCase
{
    public $correctAnswer;

    public $incorrectAnswer;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->correctAnswer = factory(Answer::class)->create([
           'answer' => 'exampleAnswer',
            'correct' => true
        ]);
        $this->incorrectAnswer = factory(Answer::class)->create([
            'answer' => 'exampleAnswer',
            'correct' => false
        ]);
    }

    public function test_checking_correct()
    {

        $this->assertTrue($this->correctAnswer->checkCorrect());
        $this->assertFalse( $this->incorrectAnswer->checkCorrect());
    }

    public function test_getting_attributes()
    {


        $this->assertEquals('exampleAnswer', $this->correctAnswer->getAnswer());
    }
}
